workflows:
  unity-ios:
    name: Deflect iOS
    instance_type: mac_mini_m2
    max_build_duration: 120
    scripts:
      - name: Get Unity
        script: |
          curl -L -o Unity.pkg "https://dl.unity3d.com/unity/2022.3.52f1/lts/2022.3.52f1pkg"
          sudo installer -verbose -pkg Unity.pkg -target /
      - name: Build iOS
        script: |
          /Applications/Unity/Hub/Editor/2022.3.52f1/Unity.app/Contents/MacOS/Unity \
            -batchmode -nographics -projectPath . \
            -buildTarget iOS -executeMethod BuildScript.BuildIos -quit
    artifacts:
      - ios/**/*
      - build/**/*
