workflows:
  unity-ios:
    name: Deflect iOS
    instance_type: mac_pro
    max_build_duration: 120
    scripts:
      - name: Get Unity
        script: |
          /usr/bin/curl -L -o unity.pkg "https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.dmg"
          hdiutil attach UnityHubSetup.dmg
          sudo /Volumes/UnityHub/UnityHub.app/Contents/MacOS/UnityHub --headless --hosted-mode
      - name: Build iOS
        script: |
          find /Applications/Unity -name Unity.app | head -1 | xargs -I {} /bin/bash -c "
            {} -batchmode -projectPath . -buildTarget iOS -executeMethod UnityEditor.BuildPlayerWindow.DefaultBuildMethods.BuildPlayer -quit
          "
    artifacts:
      - build/**/*
      - ios/builds/**/*
