workflows:
  unity-ios:
    name: Deflect iOS
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      unity: 2022.3.52f1  # Auto-installs LTS [web:330]
    scripts:
      - name: Build iOS
        script: |
          $UNITY_HOME/Contents/MacOS/Unity \
            -batchmode -nographics -projectPath . \
            -buildTarget iOS -executeMethod BuildScript.BuildIos -quit
    artifacts:
      - ios/**/*
      - build/**/*
